[package]
name = "simple-photo-organization"
version = "0.1.0"
authors = ["nickolas"]
edition = "2018"


[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'

[dependencies]
walkdir = "2"
kamadak-exif = "0.5.4"
indicatif = "0.16.0"
clap = "2.33.3"
console = "0.14.1"
rayon = "1.5.1"